@startuml
start
:وارد کردن اقلام فاکتور;
:اعمال تخفیف/حق سرویس;
:محاسبه جمع نهایی;
if (نوع تسویه؟) then (نقدی)
  :ثبت پرداخت نقدی/کارت
else (نسیه/چک/اقساط)
  :انتخاب شرایط پرداخت
endif
:ذخیره فاکتور در دیتابیس;
:تولید خودکار سند حسابداری;
if (ارسال به مودیان فعال؟) then (بله)
  :ارسال به سامانه مودیان
  if (موفق؟) then (بله)
    :نمایش UID و وضعیت
  else (خیر)
    :نمایش خطا + ذخیره برای retry
  endif
else (خیر)
endif
:چاپ فاکتور/فیش;
stop
@enduml