@startuml
' 6. Deployment Diagram
node "User PC / Company Server" {
  [Mahak .NET Desktop App] as App
  database "Local Database" as DB
}

cloud "Internet" {
  [Mahak Web Service\n(mahak-service.ir)] as MWS
}

App --> DB : Local data
App --> MWS : Send invoices
MWS --> App : Response + Remote ID
@enduml